displayName=Rapid Pets
author=RapidUrsa
description=Collect virtual eggs from creatures and hatch client-side micro companions.
tags=pet,micro,egg,collect
plugins=com.rapidursa.shoulderpets.ShoulderPetsPlugin
version=1.0.1
